version: "3.3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    networks:
      - "hdfs-net"
    ports:
      - 8080:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    networks:
      - "hdfs-net"
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    ports:
      - 8089:8088
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    networks:
      - "hdfs-net"
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    networks:
      - "hdfs-net"
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    networks:
      - "hdfs-net"
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    networks:
      - "hdfs-net"
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    networks:
      - "hdfs-net"
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  jupyter-notebook:
    container_name: jupyternb
    image: jupyter/all-spark-notebook:42f4c82a07ff
    # depends_on:
    #   - spark-master
    expose:
      - "8888"
    networks:
      - "hdfs-net"
    ports:
      - "8888:8888"
    volumes:
      - ./nbs:/home/jovyan/work/nbs
      - ./events:/tmp/spark-events
    environment:
      - "PYSPARK_PYTHON=/usr/bin/python3"
      - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"
    command: "start-notebook.sh --ip=0.0.0.0 --allow-root --notebook-dir=/home/jovyan/work/nbs --NotebookApp.token='' "

networks:
  hdfs-net:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:

